INSERT INTO Posts (user_id, img, description, created_on) VALUES ('1', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_hole_-_Messier_87_crop_max_res.jpg/800px-Black_hole_-_Messier_87_crop_max_res.jpg', 'Post 1', DATE '2022-05-12');
INSERT INTO Posts (user_id, img, description, created_on) VALUES ('1', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_hole_-_Messier_87_crop_max_res.jpg/800px-Black_hole_-_Messier_87_crop_max_res.jpg', 'Post 2', DATE '2022-05-12');
INSERT INTO Posts (user_id, img, description, created_on) VALUES ('1', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_hole_-_Messier_87_crop_max_res.jpg/800px-Black_hole_-_Messier_87_crop_max_res.jpg', 'Post 3', DATE '2022-05-12');
INSERT INTO Posts (user_id, img, description, created_on) VALUES ('2', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_hole_-_Messier_87_crop_max_res.jpg/800px-Black_hole_-_Messier_87_crop_max_res.jpg', 'Post 4', DATE '2022-05-12');
INSERT INTO Posts (user_id, img, description, created_on) VALUES ('2', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_hole_-_Messier_87_crop_max_res.jpg/800px-Black_hole_-_Messier_87_crop_max_res.jpg', 'Post 5', DATE '2022-05-12');
INSERT INTO Posts (user_id, img, description, created_on) VALUES ('2', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_hole_-_Messier_87_crop_max_res.jpg/800px-Black_hole_-_Messier_87_crop_max_res.jpg', 'Post 6', DATE '2022-05-12');

INSERT INTO Posts (user_id, img, description, created_on) VALUES ('2', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_hole_-_Messier_87_crop_max_res.jpg/800px-Black_hole_-_Messier_87_crop_max_res.jpg', 'Post 7', DATE '2022-05-12');
INSERT INTO Posts (user_id, img, description, created_on) VALUES ('2', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_hole_-_Messier_87_crop_max_res.jpg/800px-Black_hole_-_Messier_87_crop_max_res.jpg', 'Post 8', DATE '2022-05-12');
INSERT INTO Posts (user_id, img, description, created_on) VALUES ('3', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_hole_-_Messier_87_crop_max_res.jpg/800px-Black_hole_-_Messier_87_crop_max_res.jpg', 'Post 9', DATE '2022-05-12');
INSERT INTO Posts (user_id, img, description, created_on) VALUES ('6', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_hole_-_Messier_87_crop_max_res.jpg/800px-Black_hole_-_Messier_87_crop_max_res.jpg', 'Post 10', DATE '2022-05-12');
INSERT INTO Posts (user_id, img, description, created_on) VALUES ('4', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_hole_-_Messier_87_crop_max_res.jpg/800px-Black_hole_-_Messier_87_crop_max_res.jpg', 'Post 11', DATE '2022-05-12');
INSERT INTO Posts (user_id, img, description, created_on) VALUES ('2', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_hole_-_Messier_87_crop_max_res.jpg/800px-Black_hole_-_Messier_87_crop_max_res.jpg', 'Post 12', DATE '2022-05-12');
INSERT INTO Posts (user_id, img, description, created_on) VALUES ('3', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_hole_-_Messier_87_crop_max_res.jpg/800px-Black_hole_-_Messier_87_crop_max_res.jpg', 'Post 13', DATE '2022-05-12');
INSERT INTO Posts (user_id, img, description, created_on) VALUES ('2', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_hole_-_Messier_87_crop_max_res.jpg/800px-Black_hole_-_Messier_87_crop_max_res.jpg', 'Post 14', DATE '2022-05-12');
INSERT INTO Posts (user_id, img, description, created_on) VALUES ('4', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_hole_-_Messier_87_crop_max_res.jpg/800px-Black_hole_-_Messier_87_crop_max_res.jpg', 'Post 15', DATE '2022-05-12');

